name: Run CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
          cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Protoc Go plugin
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cachev3-v1
          path: | 
            .task/
            dist/
            binary_dist/
            ui/core/proto/
            sim/core/proto/

      - name: Test
        run: |
          task test
          
      - name: Build All 🔧
        run: |
          task

      - name: Deploy 🚀
        # Conditionally accept on merged PRs.
        if: ${{ github.event_name == 'push' }} 
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist/wotlk